server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitwell
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver

gemini:
  api:
    url: "https://generativelanguage.googleapis.com"  # Placeholder URL, replace with actual one later
    key: "AIzaSyAGN1qsN-ffA6FvNtkAirEZWJ98vP2XPs4"
