server:
  port: 8081

spring:
  application:
    name: Fitness-Service
  datasource:
    url: jdbc:mysql://localhost:3306/fitwell
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver

ninja:
  api:
    url: "https://api.api-ninjas.com/v1/caloriesburned"
    key: "Ku20Azv4AMSMMK7CF878Rg==KT1uuYavj2k4Pfjc"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: bf46de53d0281ba765ff3c2d4512b714c8732ac7a36c73ae61739691690bcb0c