server:
  port: 8082

spring:
  application:
    name: Diet-Service
  datasource:
    url: jdbc:mysql://localhost:3306/fitwell
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver

calorie:
  api:
    url: "https://api.calorieninjas.com/v1/nutrition"
    key: "Ku20Azv4AMSMMK7CF878Rg==dD9w3BkCef3qPoR2"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true
    fetch-registry: true


jwt:
  secret: bf46de53d0281ba765ff3c2d4512b714c8732ac7a36c73ae61739691690bcb0c