server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitwell
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver

calorie:
  api:
    url: "https://api.calorieninjas.com/v1/nutrition"
    key: "Ku20Azv4AMSMMK7CF878Rg==dD9w3BkCef3qPoR2"
