

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/fitwell
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
    register-with-eureka: true
    fetch-registry: true